import { StyleSheet } from 'react-native';
import { colors, typography, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { paddingBottom: spacing.xxl },
  center: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  banner: { height: 150, backgroundColor: colors.secondary, overflow: 'hidden' },
  bannerImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(13,11,16,0.48)',
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -44,
    marginLeft: spacing.lg,
    borderWidth: 5,
    borderColor: colors.background,
    position: 'relative',
  },
  avatarImage: { width: '100%', height: '100%', borderRadius: 44 },
  avatarText: { fontSize: 32, fontWeight: '900', color: '#fff' },
  liveAvatarBadge: {
    position: 'absolute',
    bottom: 5,
    right: -2,
    backgroundColor: colors.live,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  liveAvatarBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  identityPanel: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  name: { ...typography.h2, color: colors.textPrimary, flexShrink: 1 },
  username: { ...typography.body, color: colors.textSecondary, marginTop: 3 },
  bio: { ...typography.bodySmall, color: colors.textPrimary, lineHeight: 20, marginTop: spacing.sm },
  bioMuted: { ...typography.bodySmall, color: colors.textSecondary, marginTop: spacing.sm },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,47,110,0.16)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    marginRight: 4,
  },
  livePillText: { color: colors.primary, fontSize: 9, fontWeight: '800' },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
  },
  statWrap: {
    flex: 1,
    alignItems: 'center',
    borderRightWidth: 1,
    borderRightColor: colors.border,
  },
  statValue: { color: colors.textPrimary, fontSize: 16, fontWeight: '800' },
  statLabel: { color: colors.textSecondary, fontSize: 11, marginTop: 3 },
  actions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  actionBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
  },
  actionBtnPrimary: { backgroundColor: colors.primary },
  actionBtnOutline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  actionBtnLive: { backgroundColor: colors.primary },
  actionBtnSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  actionBtnTextOutline: { color: colors.primary },
  actionBtnTextDark: { color: colors.textPrimary, fontSize: 14, fontWeight: '800' },
  subscribeBtn: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    minHeight: 44,
    borderRadius: 13,
    backgroundColor: '#7c3aed',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  subscribeText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  createPlanBtn: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    minHeight: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: 'rgba(255,47,110,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  createPlanText: { color: colors.primary, fontSize: 15, fontWeight: '800' },
  tabsRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  tabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.sm,
  },
  tab: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
  tabActive: { color: colors.primary, fontWeight: '800' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: spacing.lg, marginBottom: spacing.lg },
  gridItem: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  gridItemSpacing: {
    marginBottom: 6,
  },
  gridItemRightZero: {
    marginRight: 0,
  },
  gridItemRightSpacing: {
    marginRight: 6,
  },
  gridImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  gridPlaceholder: {
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  lockOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.sm,
  },
  lockText: { color: '#fff', fontSize: 12, fontWeight: '700', textAlign: 'center' },
  gridViewText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  gridViewRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  emptyWrap: { alignItems: 'center', paddingVertical: 24, paddingHorizontal: spacing.lg },
  emptyIcon: { opacity: 0.6, marginBottom: 6 },
  emptyTitle: { color: colors.textSecondary, fontSize: 13 },
  empty: { ...typography.body, color: colors.textSecondary },
});
