import { StyleSheet } from 'react-native';
import { spacing } from '../../theme';

const colors = {
  background: '#0d0b10',
  surface: '#18151c',
  surfaceAlt: '#211d27',
  primary: '#ff2f6e',
  accentPurple: '#7c3aed',
  gold: '#f5b400',
  text: '#ffffff',
  textSecondary: '#9b95a3',
  border: '#2a2530',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingBottom: spacing.xl,
  },
  scrollContent: { paddingBottom: 160 },
  coverWrap: { width: '100%', position: 'relative' },
  coverImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  coverGradient: { backgroundColor: colors.accentPurple },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(13, 11, 16, 0.45)',
  },
  menuBtn: {
    position: 'absolute',
    left: spacing.md,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  editProfileBtn: {
    position: 'absolute',
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  editProfileText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  headerBlock: {
    marginTop: -52,
    paddingHorizontal: spacing.md,
  },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.md,
  },
  avatar: {
    borderWidth: 3,
    borderColor: colors.primary,
    backgroundColor: colors.surfaceAlt,
  },
  avatarPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 36, fontWeight: '800', color: colors.text },
  statsRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 4,
  },
  stat: { flex: 1, alignItems: 'center' },
  statDivider: { width: 1, height: 28, backgroundColor: colors.border },
  statValue: { color: colors.text, fontSize: 17, fontWeight: '800' },
  statLabel: { color: colors.textSecondary, fontSize: 11, marginTop: 2 },
  identityBlock: { marginTop: spacing.md },
  nameRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  name: { color: colors.text, fontSize: 22, fontWeight: '800', flexShrink: 1 },
  creatorBadge: {
    backgroundColor: 'rgba(255,47,110,0.18)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,47,110,0.35)',
  },
  creatorBadgeText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  username: { color: colors.textSecondary, fontSize: 14, marginTop: 4 },
  bio: { color: colors.text, fontSize: 13, lineHeight: 20, marginTop: spacing.sm },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: spacing.md,
  },
  quickActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.surface,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickActionPrimary: {
    backgroundColor: 'rgba(255,47,110,0.15)',
    borderColor: 'rgba(255,47,110,0.35)',
  },
  quickActionText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  quickActionTextPrimary: { color: colors.primary },
  balanceRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: spacing.md,
    marginTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  balanceCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  balanceCardAlt: {
    borderColor: 'rgba(124, 58, 237, 0.35)',
    backgroundColor: 'rgba(124, 58, 237, 0.08)',
  },
  balanceIcon: { marginBottom: 6 },
  balanceLabel: { color: colors.textSecondary, fontSize: 12 },
  balanceValue: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: 2 },
  plansSection: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  plansHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  plansTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  plansSubtitle: { color: colors.textSecondary, fontSize: 11, marginTop: 3 },
  addPlanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  addPlanText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  noPlans: { color: colors.textSecondary, fontSize: 13, paddingVertical: spacing.sm },
  plansScroll: { maxHeight: 300 },
  planCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.sm,
    marginTop: spacing.sm,
  },
  planCopy: { flex: 1, paddingRight: spacing.sm },
  planName: { color: colors.text, fontSize: 15, fontWeight: '800' },
  planPrice: { color: colors.gold, fontSize: 13, fontWeight: '700', marginTop: 2 },
  planDescription: { color: colors.textSecondary, fontSize: 12, marginTop: 4 },
  planBenefit: { color: colors.primary, fontSize: 11, fontWeight: '700', marginTop: 4 },
  editPlanBtn: { flexDirection: 'row', alignItems: 'center', gap: 3, padding: 8 },
  editPlanText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  creatorCta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(245, 180, 0, 0.35)',
    gap: 12,
  },
  creatorCtaIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(245, 180, 0, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  creatorCtaText: { flex: 1 },
  creatorCtaTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
  creatorCtaSub: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  tabsRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    marginTop: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.lg,
  },
  tabBtn: { flex: 1, alignItems: 'center', paddingBottom: spacing.sm },
  tabBtnActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
  tab: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
  tabActive: { color: colors.primary, fontWeight: '800' },
  loader: { marginVertical: 40 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.sm },
  gridItem: { borderRadius: 10, overflow: 'hidden', backgroundColor: colors.surface },
  gridItemRightGap: { marginRight: 6 },
  gridItemRightZero: { marginRight: 0 },
  gridImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  gridPlaceholder: {
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridPlaceholderIcon: { opacity: 0.5 },
  gridOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  gridViewText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  gridViewRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: spacing.lg,
  },
  emptyIcon: { fontSize: 40, marginBottom: 12, opacity: 0.6 },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '700' },
  emptySub: { color: colors.textSecondary, fontSize: 13, textAlign: 'center', marginTop: 6 },
});
