import { StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';

export const searchColors = {
  ...colors,
  background: '#0d0b10',
  surface: '#18151c',
  surfaceAlt: '#211d27',
  primary: '#ff2f6e',
  text: '#ffffff',
  textSecondary: '#9b95a3',
  border: '#2a2530',
};

export const searchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: searchColors.background,
    paddingTop: spacing.lg,
  },
  section: { marginBottom: spacing.lg },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: { color: searchColors.text, fontSize: 17, fontWeight: '700' },
  sectionLink: { color: searchColors.primary, fontSize: 13, fontWeight: '600' },
  chipsRow: { paddingLeft: spacing.md },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: searchColors.surface,
    borderWidth: 1,
    borderColor: searchColors.border,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    gap: 6,
  },
  chipIcon: { fontSize: 12, color: searchColors.textSecondary },
  chipText: { color: searchColors.text, fontSize: 13, fontWeight: '600' },
  tagsRow: { paddingLeft: spacing.md },
  tagCard: {
    width: 130,
    height: 170,
    borderRadius: 14,
    overflow: 'hidden',
    marginRight: 10,
    backgroundColor: searchColors.surfaceAlt,
  },
  tagImage: { ...StyleSheet.absoluteFillObject, resizeMode: 'cover' },
  tagImagePlaceholder: { backgroundColor: searchColors.surfaceAlt },
  tagOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  tagLabel: { color: '#fff', fontWeight: '700', fontSize: 15 },
  tagCount: { color: 'rgba(255,255,255,0.8)', fontSize: 12, marginTop: 2 },
  personRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: searchColors.surface,
    borderWidth: 1,
    borderColor: searchColors.border,
    borderRadius: 16,
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    gap: 10,
  },
  personAvatarWrap: { width: 56, height: 56 },
  personAvatar: { width: 56, height: 56, borderRadius: 28 },
  personAvatarPlaceholder: { backgroundColor: searchColors.surfaceAlt },
  personLiveTag: {
    position: 'absolute',
    bottom: -4,
    left: 6,
    backgroundColor: searchColors.primary,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  personLiveTagText: { color: '#fff', fontSize: 8, fontWeight: '700' },
  personInfo: { flex: 1, gap: 2 },
  personNameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  personName: { color: searchColors.text, fontSize: 15, fontWeight: '700' },
  personStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  personLiveBadge: {
    backgroundColor: searchColors.primary,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  personLiveBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  personViewers: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  personViewersText: { color: searchColors.textSecondary, fontSize: 12 },
  personTagline: {
    color: searchColors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  followBtn: {
    borderWidth: 1.5,
    borderColor: searchColors.primary,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  followingBtn: { backgroundColor: searchColors.primary },
  followBtnText: {
    color: searchColors.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  followingBtnText: { color: '#fff' },
  moreBtn: { paddingHorizontal: 6, paddingVertical: 8 },
  resultCard: {
    backgroundColor: searchColors.surface,
    padding: spacing.md,
    borderRadius: 18,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: searchColors.border,
    elevation: 3,
  },
  resultRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  resultAvatarWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    position: 'relative',
  },
  resultAvatar: { width: '100%', height: '100%', resizeMode: 'cover' },
  resultAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: searchColors.surfaceAlt,
  },
  resultAvatarInitial: {
    color: searchColors.text,
    fontWeight: '700',
    fontSize: 18,
  },
  resultLiveTag: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    backgroundColor: searchColors.primary,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  resultLiveTagText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  resultDetails: { flex: 1, justifyContent: 'center', gap: 4 },
  resultNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  resultTitle: {
    color: searchColors.text,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  resultSnippet: {
    color: searchColors.textSecondary,
    fontSize: 13,
    marginTop: 8,
    lineHeight: 18,
  },
  resultMeta: {
    color: searchColors.textSecondary,
    fontSize: 12,
    marginTop: 10,
  },
  empty: {
    color: searchColors.textSecondary,
    textAlign: 'center',
    marginTop: 40,
  },
});
