import { Alert, AlertIcon, Badge, Box, Button, Flex, Heading, HStack, Icon, IconButton, Input, Select, Spinner, Table, Tbody, Td, Text, Th, Thead, Tr, VStack, useToast } from "@chakra-ui/react";
import { Check, RefreshCw } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { adminRequestWithMeta, ApiRecord } from "../api/adminApi";
import { ActionButton } from "../components/ui/ActionButton";
import { Pagination } from "../components/dashboard/Pagination";

export type ResourceAction = { label: string; icon: typeof Check; path: (row: ApiRecord) => string; method?: "PATCH" | "DELETE"; body?: ApiRecord; colorScheme?: string; disabled?: (row: ApiRecord) => boolean };
type ResourcePageProps = { title: string; description: string; endpoint: (page: number, limit: number, filters: Record<string, string>) => string; columns: string[]; filters?: Array<{ key: string; label: string; options: string[] }>; actions?: ResourceAction[] };
const rowsFrom = (value: unknown): ApiRecord[] => Array.isArray(value) ? value.filter((item): item is ApiRecord => Boolean(item && typeof item === "object")) : [];
const valueOf = (row: ApiRecord, column: string) => { const value = row[column]; if (value && typeof value === "object") { const record = value as ApiRecord; return String(record.displayName || record.username || record.email || record._id || "-"); } return value === null || value === undefined || value === "" ? "-" : String(value); };
const pretty = (value: string) => value.replace(/_/g, " ");

export const AdminResourcePage = ({ title, description, endpoint, columns, filters = [], actions = [] }: ResourcePageProps) => {
  const toast = useToast(); const [rows, setRows] = useState<ApiRecord[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [search, setSearch] = useState(""); const [values, setValues] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [actionKey, setActionKey] = useState("");
  const load = async (nextPage = page) => { setLoading(true); setError(""); try { const response = await adminRequestWithMeta<ApiRecord[]>(endpoint(nextPage, 10, { search, ...values })); setRows(rowsFrom(response.data)); setPage(nextPage); const pages = response.meta?.totalPages; setTotalPages(typeof pages === "number" ? Math.max(1, pages) : 1); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : `Unable to load ${title.toLowerCase()}.`); } finally { setLoading(false); } };
  useEffect(() => { void load(1); }, [values]);
  const submit = (event: FormEvent) => { event.preventDefault(); void load(1); };
  const runAction = async (action: ResourceAction, row: ApiRecord, index: number) => { const id = String(row._id || row.id || index); setActionKey(`${action.label}-${id}`); setError(""); try { await adminRequestWithMeta(action.path(row), { method: action.method || "PATCH", body: JSON.stringify(action.body || {}) }); toast({ title: `${action.label} complete`, status: "success", duration: 2500, isClosable: true }); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : `Unable to ${action.label.toLowerCase()}.`); } finally { setActionKey(""); } };
  return <VStack align="stretch" spacing={5}><Flex justify="space-between" align={{ base: "start", sm: "center" }} direction={{ base: "column", sm: "row" }} gap={3}><Box><Heading size="lg">{title}</Heading><Text color="gray.500" mt={1}>{description}</Text></Box><Button size="sm" variant="outline" leftIcon={<RefreshCw size={15} />} onClick={() => void load()} isLoading={loading}>Refresh</Button></Flex><Flex as="form" onSubmit={submit} gap={3} wrap="wrap" bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={4} align="center"><Input placeholder="Search" value={search} onChange={(event) => setSearch(event.target.value)} maxW={{ base: "full", md: "280px" }} h="42px" />{filters.map((filter) => <Select key={filter.key} placeholder={filter.label} value={values[filter.key] || ""} onChange={(event) => setValues((current) => ({ ...current, [filter.key]: event.target.value }))} maxW={{ base: "full", sm: "180px" }} h="42px">{filter.options.map((option) => <option key={option} value={option}>{pretty(option)}</option>)}</Select>)}<ActionButton type="submit">Search</ActionButton></Flex>{error && <Alert status="error" borderRadius="8px"><AlertIcon />{error}</Alert>}<Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" overflow="hidden">{loading ? <Flex minH="220px" justify="center" align="center"><Spinner color="brand.500" /></Flex> : rows.length === 0 ? <Text p={8} color="gray.500">No records returned by the API.</Text> : <Box overflowX="auto"><Table minW="850px"><Thead bg="gray.50"><Tr>{columns.map((column) => <Th key={column}>{pretty(column)}</Th>)}{actions.length > 0 && <Th>Actions</Th>}</Tr></Thead><Tbody>{rows.map((row, index) => <Tr key={String(row._id || row.id || index)}>{columns.map((column) => <Td key={column} maxW="280px" whiteSpace="nowrap" overflow="hidden" textOverflow="ellipsis">{column.toLowerCase().includes("status") || column.toLowerCase().includes("role") || column.toLowerCase().includes("type") ? <Badge colorScheme="blue" textTransform="none">{valueOf(row, column)}</Badge> : valueOf(row, column)}</Td>)}{actions.length > 0 && <Td><HStack spacing={1}>{actions.map((action) => <IconButton key={action.label} aria-label={action.label} title={action.label} icon={<Icon as={action.icon} boxSize={4} />} size="sm" variant="ghost" colorScheme={action.colorScheme} isDisabled={action.disabled?.(row)} isLoading={actionKey === `${action.label}-${String(row._id || row.id || index)}`} onClick={() => void runAction(action, row, index)} />)}</HStack></Td>}</Tr>)}</Tbody></Table></Box>}</Box><Pagination page={page} totalPages={totalPages} onPageChange={(nextPage) => void load(nextPage)} isLoading={loading} /></VStack>;
};
