import { Alert, AlertIcon, Badge, Box, Button, Flex, FormControl, FormLabel, Heading, Select, SimpleGrid, Spinner, Text, VStack } from "@chakra-ui/react";
import { BarChart3, DollarSign, FileWarning, RefreshCw, Users } from "lucide-react";
import { ArcElement, BarElement, CategoryScale, Chart as ChartJS, Legend, LinearScale, Tooltip } from "chart.js";
import type { ChartData, ChartOptions } from "chart.js";
import { Bar, Doughnut } from "react-chartjs-2";
import { useEffect, useState } from "react";
import { adminRequest, ApiRecord, endpoint } from "../api/adminApi";
import { StatCard } from "../components/dashboard/StatCard";

ChartJS.register(ArcElement, BarElement, CategoryScale, LinearScale, Tooltip, Legend);
type AnalyticsData = { dashboard: ApiRecord; users: ApiRecord; reports: ApiRecord; financial: ApiRecord };
type Filters = { from: string; to: string; role: string; reportStatus: string; isVerified: string; isBanned: string; reportTargetType: string; reportReason: string; paymentType: string; paymentStatus: string; paymentGateway: string };
const defaults = (): Filters => { const to = new Date(); const from = new Date(to.getTime() - 86400000); return { from: from.toISOString().slice(0, 16), to: to.toISOString().slice(0, 16), role: "", reportStatus: "", isVerified: "", isBanned: "", reportTargetType: "", reportReason: "", paymentType: "", paymentStatus: "", paymentGateway: "" }; };
const valueAt = (value: unknown, path: string[]) => { let current = value; for (const key of path) { if (!current || typeof current !== "object") return 0; current = (current as ApiRecord)[key]; } return typeof current === "number" ? current : 0; };
const money = (value: number) => `INR ${(value / 100).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
const map = (value: unknown) => value && typeof value === "object" ? value as ApiRecord : {};
const barOptions: ChartOptions<"bar"> = { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true, ticks: { precision: 0 } } } };
const doughnutOptions: ChartOptions<"doughnut"> = { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: "bottom" } } };

export const AnalyticsPage = () => {
  const [filters, setFilters] = useState<Filters>(defaults); const [data, setData] = useState<AnalyticsData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const update = (key: keyof Filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const makeQuery = (keys: Array<keyof Filters>) => { const params = new URLSearchParams(); keys.forEach((key) => { if (filters[key]) params.set(key, key === "from" || key === "to" ? new Date(filters[key]).toISOString() : filters[key]); }); return params.toString(); };
  const load = async () => { setLoading(true); setError(""); try { const [dashboard, users, reports, financial] = await Promise.all([adminRequest<ApiRecord>(`${endpoint.dashboardStats}?${makeQuery(["from", "to", "role", "reportStatus"])}`), adminRequest<ApiRecord>(`${endpoint.userStats}?${makeQuery(["from", "to", "role", "isVerified", "isBanned"])}`), adminRequest<ApiRecord>(`${endpoint.reportStats}?${makeQuery(["from", "to", "reportStatus", "reportTargetType", "reportReason"])}`), adminRequest<ApiRecord>(`${endpoint.financialStats}?${makeQuery(["from", "to", "paymentType", "paymentStatus", "paymentGateway"])}`)]); setData({ dashboard, users, reports, financial }); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to load analytics."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const totalUsers = valueAt(data?.dashboard, ["users", "total"]); const banned = valueAt(data?.dashboard, ["users", "banned"]); const totalReports = valueAt(data?.dashboard, ["reports", "total"]); const pending = valueAt(data?.dashboard, ["reports", "pending"]); const posts = valueAt(data?.dashboard, ["content", "posts"]); const lives = valueAt(data?.dashboard, ["content", "liveStreams"]); const revenue = valueAt(data?.financial, ["totalRevenue"]); const payouts = valueAt(data?.financial, ["totalPayouts"]); const profit = valueAt(data?.financial, ["profit"]); const transactions = valueAt(data?.financial, ["transactionCount"]); const payoutCount = valueAt(data?.financial, ["payoutCount"]); const roles = map(data?.users?.roleDistribution); const statuses = map(data?.reports?.statusDistribution);
  const activity: ChartData<"bar"> = { labels: ["Users", "Reports", "Posts", "Live streams"], datasets: [{ data: [totalUsers, totalReports, posts, lives], backgroundColor: ["#0F8B7B", "#E86A4A", "#3182CE", "#805AD5"], borderRadius: 5 }] };
  const roleChart: ChartData<"doughnut"> = { labels: Object.keys(roles).length ? Object.keys(roles) : ["No role data"], datasets: [{ data: Object.keys(roles).length ? Object.values(roles).map((item) => typeof item === "number" ? item : 0) : [1], backgroundColor: ["#0F8B7B", "#E86A4A", "#3182CE", "#805AD5"], borderWidth: 0 }] };
  const reportChart: ChartData<"bar"> = { labels: Object.keys(statuses).length ? Object.keys(statuses) : ["No reports"], datasets: [{ data: Object.keys(statuses).length ? Object.values(statuses).map((item) => typeof item === "number" ? item : 0) : [0], backgroundColor: "#E86A4A", borderRadius: 5 }] };
  return <VStack align="stretch" spacing={5}><Flex justify="space-between" align={{ base: "start", sm: "center" }} direction={{ base: "column", sm: "row" }} gap={3}><Box><Heading size="lg">Analytics</Heading><Text color="gray.500" mt={1}>Filtered platform, user, report, and financial intelligence.</Text></Box><Button size="sm" variant="outline" leftIcon={<RefreshCw size={15} />} onClick={() => void load()} isLoading={loading}>Refresh</Button></Flex>
    <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={4}><Flex gap={4} wrap="wrap" align="end"><FormControl width={{ base: "full", md: "180px" }}><FormLabel fontSize="xs">From</FormLabel><input type="datetime-local" value={filters.from} onChange={(event) => update("from", event.target.value)} /></FormControl><FormControl width={{ base: "full", md: "180px" }}><FormLabel fontSize="xs">To</FormLabel><input type="datetime-local" value={filters.to} onChange={(event) => update("to", event.target.value)} /></FormControl><FormControl width="150px"><FormLabel fontSize="xs">Role</FormLabel><Select value={filters.role} onChange={(event) => update("role", event.target.value)}><option value="">All roles</option><option value="fan">Fan</option><option value="creator">Creator</option><option value="moderator">Moderator</option><option value="admin">Admin</option></Select></FormControl><FormControl width="160px"><FormLabel fontSize="xs">Report status</FormLabel><Select value={filters.reportStatus} onChange={(event) => update("reportStatus", event.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option></Select></FormControl><FormControl width="150px"><FormLabel fontSize="xs">Target type</FormLabel><Select value={filters.reportTargetType} onChange={(event) => update("reportTargetType", event.target.value)}><option value="">All targets</option><option value="user">User</option><option value="post">Post</option><option value="live">Live</option><option value="message">Message</option></Select></FormControl><FormControl width="160px"><FormLabel fontSize="xs">Payment type</FormLabel><Select value={filters.paymentType} onChange={(event) => update("paymentType", event.target.value)}><option value="">All payments</option><option value="coin_purchase">Coin purchase</option><option value="subscription">Subscription</option><option value="gift_sent">Gift sent</option><option value="withdrawal">Withdrawal</option><option value="refund">Refund</option></Select></FormControl><Button onClick={() => void load()} colorScheme="brand">Apply filters</Button><Button onClick={() => setFilters(defaults)} variant="ghost">Reset</Button></Flex></Box>
    {error && <Alert status="error" borderRadius="8px"><AlertIcon />{error}</Alert>}{loading && !data ? <Flex minH="220px" justify="center" align="center"><Spinner color="brand.500" /></Flex> : data && <><SimpleGrid columns={{ base: 1, sm: 2, xl: 5 }} spacing={4}><StatCard label="Total users" value={String(totalUsers)} change={`${banned} banned`} trend="up" icon={Users} color="brand" /><StatCard label="Total reports" value={String(totalReports)} change={`${pending} pending`} trend="up" icon={FileWarning} color="orange" /><StatCard label="Revenue" value={money(revenue)} change={`${transactions} transactions`} trend="up" icon={DollarSign} color="green" /><StatCard label="Payouts" value={money(payouts)} change={`${payoutCount} requests`} trend="up" icon={BarChart3} color="blue" /><StatCard label="Profit" value={money(profit)} change="Revenue less payouts" trend="up" icon={BarChart3} color="brand" /></SimpleGrid><SimpleGrid columns={{ base: 1, xl: 3 }} spacing={5}><Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={5}><Text fontWeight="800" fontSize="lg">Platform activity</Text><Box height="260px" mt={5}><Bar data={activity} options={barOptions} /></Box></Box><Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={5}><Text fontWeight="800" fontSize="lg">User roles</Text><Box height="260px" mt={5}><Doughnut data={roleChart} options={doughnutOptions} /></Box></Box><Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={5}><Text fontWeight="800" fontSize="lg">Report status</Text><Box height="260px" mt={5}><Bar data={reportChart} options={barOptions} /></Box></Box></SimpleGrid><Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="12px" p={5}><Text fontWeight="800">Analysis</Text><SimpleGrid columns={{ base: 1, md: 3 }} spacing={4} mt={4}><Text color="gray.600">{totalUsers - banned} of {totalUsers} users are active.</Text><Text color="gray.600">{pending ? `${pending} reports need review.` : "No reports are pending."}</Text><Text color="gray.600">{revenue ? `${money(profit)} net profit in this range.` : "No revenue in this range."}</Text></SimpleGrid></Box></>}
  </VStack>;
};
