import { Platform, StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 7, 18, 0.36)',
  },
  topBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 24,
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 2,
  },
  hostChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 8,
    flexShrink: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  hostAvatar: { width: 34, height: 34, borderRadius: 17 },
  hostAvatarFallback: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hostAvatarInitial: { color: '#fff', fontSize: 15, fontWeight: '800' },
  hostInfo: { marginLeft: 8, flexShrink: 1 },
  hostName: { color: '#fff', fontWeight: '700', fontSize: 13 },
  hostStatus: { color: 'rgba(255,255,255,0.78)', fontSize: 11, marginTop: 1 },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  viewerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  viewerIcon: { fontSize: 12, marginRight: 4 },
  viewerText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  closeBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  chatList: {
    position: 'absolute',
    left: spacing.md,
    bottom: 120,
  },
  chatListCompact: { right: 24 },
  chatListWide: { right: 84 },
  chatListFixedHeight: { maxHeight: 240 },
  chatListContent: { paddingBottom: 8 },
  chatRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  chatAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  chatAvatarMine: { backgroundColor: 'rgba(255,255,255,0.42)' },
  chatBubble: {
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexShrink: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  chatBubbleMine: {
    backgroundColor: 'rgba(255, 45, 85, 0.24)',
  },
  giftBubble: {
    backgroundColor: 'rgba(245, 197, 24, 0.18)',
    borderColor: 'rgba(245, 197, 24, 0.35)',
  },
  chatUser: { color: '#f5c518', fontSize: 12, fontWeight: '700' },
  chatText: { color: '#fff', fontSize: 13, marginTop: 1 },
  giftChatText: {
    color: '#fff',
    fontSize: 13,
    marginTop: 1,
    fontWeight: '600',
  },
  bottomBar: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: Platform.OS === 'ios' ? 22 : 12,
    zIndex: 2,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  input: { flex: 1, color: '#fff', fontSize: 14, paddingVertical: 2 },
  sendBtn: {
    marginLeft: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary || '#ff2d55',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  quickActions: {
    flexDirection: 'row',
    marginTop: 10,
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  quickAction: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  quickActionIcon: { fontSize: 14, marginRight: 4 },
  quickActionLabel: { color: '#fff', fontSize: 12, fontWeight: '600' },
  coinChip: {
    backgroundColor: 'rgba(245, 197, 24, 0.22)',
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(245, 197, 24, 0.4)',
  },
  coinChipText: { color: '#f5c518', fontSize: 12, fontWeight: '700' },
});
