import { StyleSheet } from 'react-native';
import { colors as baseColors, typography, spacing } from '../../theme';

const colors = {
  ...baseColors,
  background: '#0d0b10',
  surface: '#18151c',
  surfaceAlt: '#211d27',
  primary: '#ff2f6e',
  accentPurple: '#7c3aed',
  gold: '#f5b400',
  text: '#ffffff',
  textSecondary: '#9b95a3',
  border: '#2a2530',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl + spacing.lg,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  eyebrow: {
    ...typography.caption,
    color: colors.textSecondary,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  title: {
    ...typography.h1,
    color: colors.text,
    fontSize: 30,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  badgeIcon: {
    marginRight: 4,
  },
  headerBadgeText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  heroCard: {
    backgroundColor: '#1c1225',
    borderRadius: 28,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    marginBottom: spacing.xl,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 5,
  },
  heroGlow: {
    position: 'absolute',
    top: -40,
    right: -30,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.primary + '22',
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  heroTextWrap: {
    flex: 1,
  },
  heroLabel: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  heroTitle: {
    ...typography.h2,
    color: colors.text,
    flexShrink: 1,
    fontSize: 21,
    lineHeight: 28,
  },
  heroSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  formLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: spacing.sm,
  },
  heroBadgeIcon: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
  },
  modeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  modeChip: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    paddingVertical: 13,
    alignItems: 'center',
  },
  modeChipContent: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  modeChipActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(255,47,110,0.12)',
  },
  modeChipText: {
    color: colors.textSecondary,
    fontWeight: '600',
    fontSize: 13,
  },
  modeChipTextActive: {
    color: colors.primary,
  },
  inputCard: {
    gap: spacing.sm,
  },
  titleInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    fontSize: 15,
    fontWeight: '500',
  },
  vipHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  selectedGiftPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,47,110,0.1)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,47,110,0.25)',
    padding: spacing.md,
    minHeight: 76,
  },
  selectedGiftInfo: {
    flex: 1,
  },
  selectedGiftEmoji: {
    fontSize: 36,
  },
  selectedGiftTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  selectedGiftMeta: {
    color: colors.gold,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  coinMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  vipGrid: {
    flexDirection: 'row',
    gap: spacing.sm ?? 8,
    marginBottom: spacing.md,
  },
  liveGrid: {
    flexDirection: 'row',
    gap: spacing.sm ?? 8,
    paddingBottom: spacing.md,
  },
  roomSection: { marginTop: spacing.sm },
  vipStartBtnOverlay: {
    backgroundColor: colors.accentPurple,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: -4,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalEyebrow: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    textAlign: 'center',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 6,
  },
  modalHost: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: spacing.md,
  },
  modalGiftBubble: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,47,110,0.1)',
    borderRadius: 20,
    paddingVertical: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,47,110,0.25)',
    marginBottom: spacing.md,
  },
  modalGiftEmoji: { fontSize: 56 },
  modalGiftName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
  },
  modalGiftCost: {
    color: colors.gold,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  modalCoinRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  modalHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  modalPayBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  modalPayBtnDisabled: { opacity: 0.7 },
  modalPayBtnText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  modalCancelBtn: { alignItems: 'center', paddingVertical: spacing.md },
  modalCancelText: { color: colors.textSecondary, fontWeight: '600' },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: spacing.md,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
  },
  sectionTitle: {
    ...typography.h3,
    color: colors.text,
  },
  sectionHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  roomList: {
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  roomCard: {
    width: 220,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  roomImage: {
    width: '100%',
    height: 160,
    resizeMode: 'cover',
  },
  roomOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: spacing.sm,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  roomTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  roomStats: {
    flexDirection: 'row',
    gap: 6,
  },
  livePillSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.live,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  livePillText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    marginLeft: 4,
  },
  viewerText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  roomInfo: {
    gap: 2,
  },
  roomTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  roomHost: {
    color: '#f7f7f7',
    fontSize: 12,
    fontWeight: '600',
  },
  vipCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  vipCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  vipCardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  vipCardMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  vipCardSchedule: {
    color: colors.gold,
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
  },
  vipStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  vipStatusLive: {
    backgroundColor: colors.primary,
  },
  vipStatusWaiting: {
    backgroundColor: colors.accentPurple,
  },
  vipStatusText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  vipJoinBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  vipJoinBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  vipStartBtn: {
    backgroundColor: colors.accentPurple,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  vipStartBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  vipFullText: {
    color: colors.textSecondary,
    fontSize: 13,
    textAlign: 'center',
  },
  loadingCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    paddingVertical: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
    marginTop: spacing.sm,
  },
  emptySubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  liveDotSmall: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#fff',
  },
});
