import { Platform, StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 7, 18, 0.36)',
  },
  topBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 24,
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 5,
  },
  hostChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 8,
    flexShrink: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  hostAvatar: { width: 34, height: 34, borderRadius: 17 },
  hostAvatarFallback: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hostAvatarInitial: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  hostInfo: { marginLeft: 8, flexShrink: 1 },
  hostName: { color: '#fff', fontWeight: '700', fontSize: 13 },
  hostStatus: { color: 'rgba(255,255,255,0.78)', fontSize: 11, marginTop: 1 },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  earningsChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 197, 24, 0.22)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(245, 197, 24, 0.45)',
  },
  earningsText: { color: '#f5c518', fontSize: 12, fontWeight: '800' },
  viewerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  viewerIcon: { fontSize: 12, marginRight: 4 },
  viewerText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  closeBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
  },
  headerBackBtn: {
    marginLeft: 4,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  headerBackText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '700',
  },
  heartsColumn: {
    position: 'absolute',
    right: spacing.md,
    bottom: 150,
    width: 40,
    height: 260,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  chatSticky: {
    position: 'absolute',
    left: spacing.md,
    bottom: 82,
  },
  chatList: { flex: 1 },
  chatListCompact: {
    right: 24,
  },
  chatListWide: {
    right: 84,
  },
  chatListContent: { paddingBottom: 8 },
  joinToast: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(120, 80, 200, 0.68)',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  joinToastText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  chatRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  chatAvatar: { width: 30, height: 30, borderRadius: 15, marginRight: 8 },
  chatAvatarFallback: { backgroundColor: 'rgba(255,255,255,0.28)' },
  chatBubble: {
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexShrink: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  chatUser: { color: '#f5c518', fontSize: 12, fontWeight: '700' },
  chatText: { color: '#fff', fontSize: 13, marginTop: 1 },
  commentActions: { flexDirection: 'row', alignItems: 'center', position: 'relative', maxWidth: '92%' },
  commentMenuButton: {
    width: 28,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  commentMenu: {
    position: 'absolute',
    top: 34,
    right: 0,
    minWidth: 148,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: '#171827',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 20,
    elevation: 8,
  },
  commentMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 9,
    gap: 8,
  },
  commentMenuText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  blockMenuText: { color: '#ff6b81' },
  giftBubble: {
    backgroundColor: 'rgba(245, 197, 24, 0.18)',
    borderColor: 'rgba(245, 197, 24, 0.35)',
  },
  giftChatText: { color: '#fff', fontSize: 13, marginTop: 1, fontWeight: '600' },
  bottomBar: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    bottom: Platform.OS === 'ios' ? 22 : 12,
    zIndex: 6,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  moreButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  input: { flex: 1, color: '#fff', fontSize: 14, paddingVertical: 2, marginLeft: 8 },
  sendBtn: {
    marginLeft: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary || '#ff2d55',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionDrawer: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    bottom: 68,
    paddingTop: 8,
    paddingBottom: 10,
    borderRadius: 22,
    backgroundColor: 'rgba(15, 23, 42, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    zIndex: 8,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 7,
  },
  drawerHandle: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.42)',
    marginBottom: 8,
  },
  drawerOptions: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  drawerOption: {
    minWidth: 112,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  drawerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  drawerLabel: { color: '#fff', fontSize: 12, fontWeight: '700', marginTop: 6 },
  revealButton: {
    position: 'absolute',
    right: 12,
    top: '50%',
    marginTop: -24,
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 8,
  },
});
