import React from 'react';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AuthStackParamList } from '../../navigation/types';
import { colors, spacing, typography } from '../../theme';

type Props = NativeStackScreenProps<AuthStackParamList, 'LegalDocument'>;
type DocumentLine = { text: string; kind: 'title' | 'meta' | 'heading' | 'subheading' | 'body' | 'bullet' };

const privacyPolicy: DocumentLine[] = [
  { text: 'Zemin Privacy Policy', kind: 'title' },
  { text: 'Last Updated: September 8, 2026', kind: 'meta' },
  { text: 'Zemin ("Zemin", "we", "our", or "us") respects your privacy. This Privacy Policy explains how we collect, use, store, and protect information when you use the Zemin mobile application and related services ("Service").', kind: 'body' },
  { text: 'By using Zemin, you agree to the practices described in this Privacy Policy.', kind: 'body' },
  { text: '1. Information We Collect', kind: 'heading' },
  { text: 'Depending on the features you use, Zemin may collect:', kind: 'body' },
  { text: 'Account Information', kind: 'subheading' },
  { text: 'Name or username', kind: 'bullet' },
  { text: 'Email address', kind: 'bullet' },
  { text: 'Mobile phone number', kind: 'bullet' },
  { text: 'Profile photo', kind: 'bullet' },
  { text: 'Date of birth or age information', kind: 'bullet' },
  { text: 'Password or authentication information', kind: 'bullet' },
  { text: 'User-Generated Content', kind: 'subheading' },
  { text: 'Profile information', kind: 'bullet' },
  { text: 'Photos and videos', kind: 'bullet' },
  { text: 'Live-stream content', kind: 'bullet' },
  { text: 'Comments and messages', kind: 'bullet' },
  { text: 'Reports and moderation information', kind: 'bullet' },
  { text: 'Device and Technical Information', kind: 'subheading' },
  { text: 'Device model', kind: 'bullet' },
  { text: 'Operating system', kind: 'bullet' },
  { text: 'App version', kind: 'bullet' },
  { text: 'IP address', kind: 'bullet' },
  { text: 'Device identifiers', kind: 'bullet' },
  { text: 'Crash and diagnostic information', kind: 'bullet' },
  { text: 'Log information', kind: 'bullet' },
  { text: 'Location Information', kind: 'subheading' },
  { text: 'If you enable location-related features, we may collect approximate or precise location information as permitted by your device permissions.', kind: 'body' },
  { text: 'Transaction Information', kind: 'subheading' },
  { text: 'If Zemin provides coins, gifts, subscriptions, or other paid features, we may process information necessary to operate those transactions.', kind: 'body' },
  { text: 'Payment card, UPI, or other payment details may be processed by the applicable payment provider or app store rather than being directly stored by Zemin.', kind: 'body' },
  { text: '2. Camera, Microphone and Media Permissions', kind: 'heading' },
  { text: 'Zemin may request access to your camera and microphone when you use features such as live streaming or video communication.', kind: 'body' },
  { text: 'We use these permissions only to provide the requested features and related safety/moderation functions.', kind: 'body' },
  { text: 'You can manage these permissions through your device settings.', kind: 'body' },
  { text: '3. How We Use Information', kind: 'heading' },
  { text: 'We may use collected information to:', kind: 'body' },
  { text: 'Create and manage accounts', kind: 'bullet' },
  { text: 'Provide live-streaming and social features', kind: 'bullet' },
  { text: 'Connect users with other users', kind: 'bullet' },
  { text: 'Process purchases and virtual items', kind: 'bullet' },
  { text: 'Prevent fraud and abuse', kind: 'bullet' },
  { text: 'Detect prohibited or unsafe content', kind: 'bullet' },
  { text: 'Moderate live streams and user-generated content', kind: 'bullet' },
  { text: 'Respond to reports and complaints', kind: 'bullet' },
  { text: 'Provide customer support', kind: 'bullet' },
  { text: 'Improve application performance', kind: 'bullet' },
  { text: 'Detect technical problems', kind: 'bullet' },
  { text: 'Maintain security', kind: 'bullet' },
  { text: 'Comply with legal requirements', kind: 'bullet' },
  { text: '4. Content Moderation', kind: 'heading' },
  { text: 'Zemin may use automated systems and human moderation to identify prohibited content, including nudity, sexually explicit content, abuse, harassment, fraud, and other violations of our Terms of Service.', kind: 'body' },
  { text: 'Live streams or accounts that violate our rules may be restricted, terminated, suspended, or permanently banned.', kind: 'body' },
  { text: '5. How We Share Information', kind: 'heading' },
  { text: 'We may share information with:', kind: 'body' },
  { text: 'Service providers that help operate Zemin', kind: 'bullet' },
  { text: 'Cloud hosting and storage providers', kind: 'bullet' },
  { text: 'Payment processors', kind: 'bullet' },
  { text: 'Analytics and security providers', kind: 'bullet' },
  { text: 'Content moderation providers', kind: 'bullet' },
  { text: 'Law enforcement or government authorities when legally required', kind: 'bullet' },
  { text: 'Other parties when necessary to protect users, Zemin, or the public', kind: 'bullet' },
  { text: 'We do not sell personal information to third parties for their own unrelated purposes.', kind: 'body' },
  { text: '6. Data Security', kind: 'heading' },
  { text: 'We use reasonable technical and organizational measures to protect your information against unauthorized access, alteration, disclosure, or destruction.', kind: 'body' },
  { text: 'However, no internet or electronic storage system can be guaranteed to be completely secure.', kind: 'body' },
  { text: '7. Data Retention', kind: 'heading' },
  { text: 'We retain information only for as long as reasonably necessary to provide the Service, maintain security, resolve disputes, enforce our terms, comply with legal obligations, and satisfy legitimate business requirements.', kind: 'body' },
  { text: "8. Children's Privacy", kind: 'heading' },
  { text: 'Zemin is intended only for people who are 18 years of age or older.', kind: 'body' },
  { text: 'By creating an account, you confirm that you are at least 18 years old.', kind: 'body' },
  { text: 'We do not knowingly allow anyone under 18 to use the Service.', kind: 'body' },
  { text: 'If we learn that an account belongs to someone under 18, we may suspend or delete the account.', kind: 'body' },
  { text: '9. Your Choices and Rights', kind: 'heading' },
  { text: 'Depending on applicable law, you may have rights to:', kind: 'body' },
  { text: 'Access your personal information', kind: 'bullet' },
  { text: 'Correct inaccurate information', kind: 'bullet' },
  { text: 'Request deletion of your account or information', kind: 'bullet' },
  { text: 'Withdraw certain permissions', kind: 'bullet' },
  { text: 'Object to or restrict certain processing', kind: 'bullet' },
  { text: 'Request information about how your data is used', kind: 'bullet' },
  { text: 'Some information may need to be retained where required by law or for legitimate security and fraud-prevention purposes.', kind: 'body' },
  { text: '10. Account Deletion', kind: 'heading' },
  { text: 'You may request deletion of your Zemin account through the account settings or by contacting us.', kind: 'body' },
  { text: 'When an account is deleted, we will delete or anonymize applicable personal information subject to legal, security, fraud-prevention, and dispute-resolution requirements.', kind: 'body' },
  { text: '11. Third-Party Services', kind: 'heading' },
  { text: 'Zemin may use third-party services for hosting, authentication, analytics, payments, notifications, content moderation, streaming, and security.', kind: 'body' },
  { text: 'Those services may process information according to their own privacy policies.', kind: 'body' },
  { text: '12. Changes to This Privacy Policy', kind: 'heading' },
  { text: 'We may update this Privacy Policy from time to time.', kind: 'body' },
  { text: 'When we make material changes, we may provide an appropriate notice through the application or other reasonable means.', kind: 'body' },
  { text: '13. Contact Us', kind: 'heading' },
  { text: 'For privacy questions, requests, or complaints, contact:', kind: 'body' },
  { text: 'Zemin Support', kind: 'subheading' },
  { text: 'Email: [YOUR SUPPORT EMAIL]', kind: 'body' },
  { text: 'Company/Owner: [YOUR LEGAL COMPANY NAME]', kind: 'body' },
  { text: 'Address: [YOUR BUSINESS ADDRESS]', kind: 'body' },
];

const termsOfService: DocumentLine[] = [
  { text: 'Zemin Terms of Service', kind: 'title' },
  { text: 'Last Updated: September 8, 2026', kind: 'meta' },
  { text: 'Welcome to Zemin.', kind: 'body' },
  { text: 'These Terms of Service ("Terms") govern your access to and use of the Zemin application and related services.', kind: 'body' },
  { text: 'By creating an account or using Zemin, you agree to these Terms.', kind: 'body' },
  { text: '1. Eligibility', kind: 'heading' },
  { text: 'You must be at least 18 years old to create an account or use Zemin.', kind: 'body' },
  { text: 'Zemin is not intended for anyone under 18.', kind: 'body' },
  { text: 'Zemin may require age verification or other verification measures for certain features.', kind: 'body' },
  { text: 'You must provide accurate information when creating your account.', kind: 'body' },
  { text: 'You are responsible for maintaining the security of your account.', kind: 'body' },
  { text: '2. User Accounts', kind: 'heading' },
  { text: 'You may not:', kind: 'body' },
  { text: 'Create an account using false information', kind: 'bullet' },
  { text: 'Impersonate another person', kind: 'bullet' },
  { text: 'Share your account with another person', kind: 'bullet' },
  { text: "Attempt to access another user's account", kind: 'bullet' },
  { text: 'Create accounts to evade a suspension or ban', kind: 'bullet' },
  { text: 'We may suspend or terminate accounts that violate these Terms.', kind: 'body' },
  { text: '3. Live Streaming', kind: 'heading' },
  { text: 'Zemin allows eligible users to create and participate in live streams.', kind: 'body' },
  { text: 'When streaming, you are responsible for all content you broadcast.', kind: 'body' },
  { text: 'You must not use Zemin to broadcast illegal, harmful, abusive, sexually explicit, or otherwise prohibited content.', kind: 'body' },
  { text: '4. Prohibited Content', kind: 'heading' },
  { text: 'The following content is prohibited:', kind: 'body' },
  { text: 'Nudity', kind: 'bullet' },
  { text: 'Pornographic or sexually explicit content', kind: 'bullet' },
  { text: 'Sexual solicitation', kind: 'bullet' },
  { text: 'Sexual exploitation', kind: 'bullet' },
  { text: 'Content involving minors in a sexual context', kind: 'bullet' },
  { text: 'Graphic violence', kind: 'bullet' },
  { text: 'Promotion of illegal activities', kind: 'bullet' },
  { text: 'Terrorist or extremist content', kind: 'bullet' },
  { text: 'Harassment or threats', kind: 'bullet' },
  { text: 'Hate-based abuse', kind: 'bullet' },
  { text: 'Fraud or scams', kind: 'bullet' },
  { text: 'Impersonation', kind: 'bullet' },
  { text: 'Content that infringes intellectual property rights', kind: 'bullet' },
  { text: 'Any content prohibited by applicable law', kind: 'bullet' },
  { text: 'Zemin may automatically detect or manually review content to enforce these rules.', kind: 'body' },
  { text: '5. Content Moderation', kind: 'heading' },
  { text: 'We may use automated moderation systems and human moderators.', kind: 'body' },
  { text: 'If prohibited content is detected or reported, we may:', kind: 'body' },
  { text: 'Stop a live stream', kind: 'bullet' },
  { text: 'Remove content', kind: 'bullet' },
  { text: 'Restrict an account', kind: 'bullet' },
  { text: 'Temporarily suspend an account', kind: 'bullet' },
  { text: 'Permanently ban an account', kind: 'bullet' },
  { text: 'Remove access to certain features', kind: 'bullet' },
  { text: 'Take other appropriate enforcement actions', kind: 'bullet' },
  { text: 'Zemin may take immediate action when necessary to protect users or comply with law.', kind: 'body' },
  { text: '6. Reporting', kind: 'heading' },
  { text: 'Users can report content or accounts that violate these Terms.', kind: 'body' },
  { text: 'False, malicious, or abusive reporting may itself result in enforcement action.', kind: 'body' },
  { text: '7. Virtual Coins, Gifts and Paid Features', kind: 'heading' },
  { text: 'Zemin may provide virtual coins, gifts, subscriptions, or other digital features.', kind: 'body' },
  { text: 'Virtual items:', kind: 'body' },
  { text: 'Have no cash value unless explicitly stated by Zemin', kind: 'bullet' },
  { text: 'Cannot be transferred outside the Service', kind: 'bullet' },
  { text: 'Cannot be used as a substitute for legal currency', kind: 'bullet' },
  { text: 'May be subject to additional purchase and refund rules', kind: 'bullet' },
  { text: 'All purchases are subject to the applicable app-store and payment-provider terms.', kind: 'body' },
  { text: '8. Creator Earnings', kind: 'heading' },
  { text: 'If Zemin provides creator monetization or withdrawal features, eligibility, rates, minimum withdrawal amounts, verification requirements, fees, and payment methods may be specified separately.', kind: 'body' },
  { text: 'Zemin may require identity, age, payment, tax, or other verification before processing withdrawals.', kind: 'body' },
  { text: '9. User Content', kind: 'heading' },
  { text: 'You retain ownership of content you create, subject to the rights necessary for Zemin to operate the Service.', kind: 'body' },
  { text: 'By uploading or broadcasting content, you grant Zemin the necessary license to host, process, transmit, display, reproduce, and distribute that content as required to provide the Service.', kind: 'body' },
  { text: 'You confirm that you have the necessary rights to the content you upload or broadcast.', kind: 'body' },
  { text: '10. Intellectual Property', kind: 'heading' },
  { text: 'The Zemin application, branding, logos, software, design, and other proprietary materials are owned by or licensed to Zemin.', kind: 'body' },
  { text: 'You may not copy, modify, reverse engineer, distribute, sell, or misuse the Service except as permitted by law.', kind: 'body' },
  { text: '11. Privacy', kind: 'heading' },
  { text: 'Your use of Zemin is also governed by our Privacy Policy.', kind: 'body' },
  { text: '12. Account Termination', kind: 'heading' },
  { text: 'We may suspend or terminate your account if:', kind: 'body' },
  { text: 'You violate these Terms', kind: 'bullet' },
  { text: 'You violate applicable law', kind: 'bullet' },
  { text: 'You engage in fraud or abuse', kind: 'bullet' },
  { text: 'You repeatedly violate community rules', kind: 'bullet' },
  { text: 'Your activity creates a safety or security risk', kind: 'bullet' },
  { text: '13. Disclaimers', kind: 'heading' },
  { text: 'Zemin is provided on an "as available" basis.', kind: 'body' },
  { text: 'We do not guarantee that the Service will always be available, uninterrupted, or error-free.', kind: 'body' },
  { text: 'We are not responsible for user-generated content posted or broadcast by users, except to the extent required by applicable law.', kind: 'body' },
  { text: '14. Limitation of Liability', kind: 'heading' },
  { text: 'To the maximum extent permitted by applicable law, Zemin will not be liable for indirect, incidental, special, consequential, or similar damages arising from use of the Service.', kind: 'body' },
  { text: 'Nothing in these Terms limits rights or liabilities that cannot legally be excluded.', kind: 'body' },
  { text: '15. Changes to Terms', kind: 'heading' },
  { text: 'We may modify these Terms from time to time.', kind: 'body' },
  { text: 'Continued use of Zemin after updated Terms become effective constitutes acceptance of the updated Terms, where permitted by law.', kind: 'body' },
  { text: '16. Contact', kind: 'heading' },
  { text: 'For questions regarding these Terms:', kind: 'body' },
  { text: 'Zemin Support', kind: 'subheading' },
  { text: 'Email: zeminApp@gamil.com', kind: 'body' },
  // { text: 'Company/Owner: [YOUR LEGAL COMPANY NAME]', kind: 'body' },
//   { text: 'Address: [YOUR BUSINESS ADDRESS]', kind: 'body' },
];

export const LegalDocumentScreen = ({ navigation, route }: Props) => {
  const isPrivacy = route.params.type === 'privacy';
  const lines = isPrivacy ? privacyPolicy : termsOfService;

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => navigation.goBack()} style={styles.backButton} accessibilityRole="button" accessibilityLabel="Go back">
          <Text style={styles.backText}>Back</Text>
        </Pressable>
        <Text style={styles.headerTitle}>{isPrivacy ? 'Privacy Policy' : 'Terms of Service'}</Text>
        <View style={styles.headerSpacer} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        {lines.map((line, index) => (
          <Text key={`${line.kind}-${index}`} style={styles[line.kind]}>{line.kind === 'bullet' ? `• ${line.text}` : line.text}</Text>
        ))}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { minHeight: 56, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border },
  backButton: { minWidth: 56, paddingVertical: spacing.sm },
  backText: { ...typography.bodySmall, color: colors.primary },
  headerTitle: { ...typography.h3, color: colors.textPrimary, flex: 1, textAlign: 'center' },
  headerSpacer: { minWidth: 56 },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  title: { ...typography.h1, color: colors.textPrimary, marginBottom: spacing.xs },
  meta: { ...typography.caption, color: colors.textDisabled, marginBottom: spacing.lg },
  heading: { ...typography.h2, color: colors.textPrimary, marginTop: spacing.lg, marginBottom: spacing.sm },
  subheading: { ...typography.h3, color: colors.textPrimary, marginTop: spacing.md, marginBottom: spacing.xs },
  body: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.md },
  bullet: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.sm, paddingLeft: spacing.sm },
});
